env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - airbnb
  - react-app
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
   "react/no-unescaped-entities": 0,
   "react/jsx-filename-extension": 0,
   "react/jsx-props-no-spreading": 0,
}
